### ISSUE TITLE
Add support for npm5

### ISSUE THREAD

**Issue by Lange** [mjeanroy/bower-npm-resolver#19]
Hello! :wave:

I seem to be unable to install any packages from npm. Both of these situations fail:
1) `bower install --save npm:nodecg-widget-obs`
2) Adding `npm:nodecg-widget-obs` to my `bower.json` dependencies and running `bower install`

Additionally, it seems that having any `npm:` dependencies in `bower.json` prevents _all_ `bower install` commands from working. They run without error, but no files are created and no `bower_components` folder is made.

I have tried this with other npm packages and the issue is unchanged.

Thanks for your time and for making this very helpful resolver!

**Comment by Lange** [comment]
Oh, I should add that I'm using Node 8 and npm 5, if that matters.

**Comment by mjeanroy** [comment]
@Lange Can you try with Node 7 and npm < 5?

I did not have the time to test against npm 5 yet, so I would like to confirm if this is due to an incompatibility with the new version of npm ;)

**Comment by Lange** [comment]
It does indeed work as expected with Node v7.10.0 and npm v4.2.0. This looks to be a problem only when running with npm 5.

**Comment by mjeanroy** [comment]
@Lange The problem was due to a change in the `npm.commands.cache.add` function that returns a promise since NPM 5.0.0 instead of using the callback parameter. The problem should be fixed with `bower-npm-resolve@0.8.0` (should be available on NPM).

Please reopen if it does not work for you, and thanks for your report!

**Comment by Lange** [comment]
Thanks! Unfortunately, I am now receiving a different error:

```
bower npm:nodecg-widget-obs#2.0.2                                               ENOENT ENOENT: no such file or directory, open 'C:\Users\vanca\AppData\Roaming\npm-cache\nodecg-widget-obs\2.0.2\package.tgz'

Stack trace:
Error: ENOENT: no such file or directory, open 'C:\Users\vanca\AppData\Roaming\npm-cache\nodecg-widget-obs\2.0.2\package.tgz'

Console trace:
Error
    at StandardRenderer.error (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:115:13)
    at Logger.emit (events.js:210:7)
    at Logger.emit (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
    at C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:137:13)
    at flush (C:\Users\vanca\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
System info:
Bower version: 1.8.0
Node version: 8.0.0
OS: Windows_NT 10.0.15063 x64
```

This still occurs after running `npm cache verify`.

**Comment by mjeanroy** [comment]
@Lange Sorry, it should be fixed with `bower-npm-resolver@0.8.1`. Please comment if it does not work for you, I'll reopen the issue.

**Comment by Lange** [comment]
It works! Thanks so much :tada:
