### ISSUE TITLE
Does not work with npm 5.6.0

### ISSUE THREAD

**Issue by Lange** [mjeanroy/bower-npm-resolver#79]
When npm 5.6.0 is installed, having _any_ `npm:` packages in `bower.json` will prevent _any_ packages from successfully being extracted to `bower_components`. The `bower_components` folder won't even be created.

It is okay on the previous release of npm, v5.5.1.

**Comment by mjeanroy** [comment]
Hi,
Thanks for the report!
It should be fixed with version 0.8.2.
Please comment or repoen the issue if not.

Thanks!

**Comment by vileppanen** [comment]
I'm still experiencing this issue, with node 6.11.3 and npm 5.6.0.

I have a scoped package as dependency in bower.json:
`"mypackage": "@my/package#1.0.0"` --> results in "E404 404 Not Found: @my/package#1.0.0"

If I install for example Node 7.10.1 and npm 4.2.0, the installation goes fine.

**Comment by mjeanroy** [comment]
@vileppanen Would you be able to send me a project to reproduce?

**Comment by gigaga** [comment]
+1
Same issue with npm 5.6.0. That works fine with npm 5.5.1

**Comment by mjeanroy** [comment]
Hi,
I will need more details to fix your issue:
- What version of `bower-npm-resolver` are you using?
- Is `bower-npm-resolver` installed globally or locally?
- What version of bower are you using?
- What dependencies are you trying to fetch?

Note that npm 5.6.0 is supported with version *0.8.2* (if you installed bower-npm-resolver globally, check it, otherwise please check the version of your package in your `node_modules` directory).

You can send me a a project with the issues, that would be perfect as I can't reproduce (feel free to test with this test project: https://github.com/mjeanroy/bower-npm-resolver-test).

**Comment by diachedelic** [comment]
I am having the same issue with a package hosted on my private NPM registry - it appears to resolve the version of the package fine but then fails with a 404 error

```
bower invalid-meta  for:/Users/diachedelic/Code/com06 Webapp/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower npm-resolver  initializing bower-npm-resolver 0.9.0
bower npm-resolver  found matchers: [{"regexp":{},"replace":""},{"regexp":{},"replace":""}]
bower npm-resolver  checking for: npm:@myscope/format
bower not-cached    npm:@myscope/format#^3.0.0
bower resolve       npm:@myscope/format#^3.0.0
bower npm-resolver  extracting package name from: npm:@myscope/format
bower npm-resolver  fetching releases information from: @myscope/format
bower npm-resolver  found releases: 1.6.2,1.6.3,2.0.0,2.0.1,2.1.2,2.2.0,2.2.1,2.3.0,2.4.0,2.4.1,3.0.0
bower npm-resolver  fetching: {"name":"crosscountry-formatters","target":"3.0.0","source":"npm:@myscope/format"}
bower npm-resolver  extracting package name from: npm:@myscope/format
bower npm-resolver  downloading tarball for: @myscope/format#3.0.0
bower E404          404 Not Found: @myscope/format@3.0.0

Stack trace:
Error: 404 Not Found: @myscope/format@3.0.0
    at fetch.then.res (/Users/diachedelic/Code/com06 Webapp/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From previous event:
    at PackageRepository.fetch (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/PackageRepository.js:46:14)
    at Manager._fetch (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Manager.js:382:10)
    at Array.forEach (<anonymous>)
    at Manager.resolve (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Manager.js:127:23)
    at Project._bootstrap (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Project.js:672:10)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Project.js:83:25
From previous event:
    at Manager.resolve (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Manager.js:119:24)
    at Project._bootstrap (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Project.js:672:10)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Project.js:83:25
From previous event:
    at Project.install (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/core/Project.js:91:10)
    at install (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/commands/install.js:29:20)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/commands/index.js:33:28
From previous event:
    at withLogger (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/commands/index.js:40:14)
    at Function.runFromArgv [as line] (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/commands/index.js:30:16)
    at Object.<anonymous> (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/bin/bower.js:83:26)

Console trace:
Error
    at StandardRenderer.error (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/renderers/StandardRenderer.js:88:37)
    at Logger.<anonymous> (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/bin/bower.js:113:30)
    at emitOne (events.js:116:13)
    at Logger.emit (events.js:211:7)
    at Logger.emit (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/commands/index.js:49:24
    at _rejected (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:864:24)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:890:30
    at Promise.when (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:808:41)
    at /Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:624:44
    at runSingle (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/Users/diachedelic/.nvm/versions/node/v8.9.0/lib/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
System info:
Bower version: 1.8.4
Node version: 8.9.0
OS: Darwin 16.7.0 x64
```

**Comment by diachedelic** [comment]
My NPM is v5.8.0

**Comment by diachedelic** [comment]
Log from my NPM registry (Verdaccio v2.5.1):

`2018-04-18T03:32:53.633Z http <-- 200, user: staff(1.144.xxx.xxx via 127.0.0.1), req: 'GET /@myscope%2fformat/-/format-3.0.0.tgz', bytes: 0/89745`

**Comment by felipemrodrigues** [comment]
I have the same issue.

**Comment by mjeanroy** [comment]
@felipemrodrigues Can you send me a reproducible repo?

**Comment by felipemrodrigues** [comment]
Unfortunately, it's not on a public repository but I'll work to have one this week.

**Comment by mjeanroy** [comment]
Hi @felipemrodrigues,
Version 0.11.0 has been published with a fix for custom registries, can you test with this version please?
